language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

before_install:
    - composer self-update
    - composer install --verbose --prefer-source --no-interaction -o

script:
    - ./vendor/bin/phpcs --standard=tests/phpcs.xml library/
    - ./vendor/bin/phpunit --configuration=tests

notifications:
    email: false

matrix:
  allow_failures:
    - php: hhvm

sudo: false
