<?php require_once "Views/template/header.phtml";?>
<main role="main" class="container">
    <div class="starter-template">
        <h1>Connecting via Phillips HUE emulator</h1>
        <p>Prerequisites</p>
        <p>1) Download the Phillips HUE emulator: <a href="https://steveyo.github.io/Hue-Emulator/" target="_blank">https://steveyo.github.io/Hue-Emulator/</a></p>
        <br><p>How to use</p>
        <p>1) Open up the Phillips HUE emulator and start it on port: 80</p><img src="../images/hueemulatorport80.png" style="height: 20rem; width: 32rem">
        <br><br><p>2) Goto www.jacklewis.xyz/huemongous and connect with the following credentials</p>
        <p>IP address: <b>localhost</b><br>Username: <b>newdeveloper</p></b><img src="../images/connectpage.png" style="height: 25rem; width: 45rem">
    
    </div>
</main>
<?php require_once "Views/template/footer.phtml";?>
