<?php require_once "Views/template/header.phtml";?>

<main role="main" class="container">
    <div class="starter-template">
        <h1>Connect</h1>
        <form method="post">
            <br>IP Address:
            <input type="text" name="host"><br>
            <br>Username:
            <input type="text" name="username"><br>
            <br><button type="submit" class="btn btn-success" name="submitConnect">Connect</button>
        </form>
    </div>
</main>

<?php require_once "Views/template/footer.phtml";?>
