<footer class="page-footer font-small special-color-dark pt-4">
    <div class="footer-copyright text-center py-3">© 2020 Jack Lewis:
        <a href="https://jacklewis.xyz/huemongous"> jacklewis.xyz/huemongous</a>
    </div>
</footer>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

